name: Inputs and Outputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Skip deployment and only print build output"
        required: true
        default: false
        type: boolean
      target:
        description: "Which environment the workflow will target"
        required: true
        type: environment
      tag:
        description: "Release from which to build and deploy"
        required: true
        default: v3
        type: choice
        options:
          - v1
          - v2
          - v3
      build-status:
        description: "Choose the build status for the demo"
        required: true
        default: success
        type: choice
        options:
          - success
          - failure

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "GITHUB_OUTPUT path:$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT

    outputs:
      build-status: ${{ steps.build.outputs.status }}
      tag: ${{ inputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' && inputs.dry-run == 'false' && needs.build.outputs.build-status == 'success' }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying to '${{ inputs.target }}' using tag '${{ needs.build.outputs.tag }}'"
